development:
  access_key_id: 'AKIAI26QEXW47MNFPGBA'
  secret_access_key: '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'
  bucket: 'campusdream'
test:
  access_key_id: 'AKIAI26QEXW47MNFPGBA'
  secret_access_key: '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'
  bucket: 'campusdream'
production:
  access_key_id: 'AKIAI26QEXW47MNFPGBA'
  secret_access_key: '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'
  bucket: 'campusdream'